# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-28 03:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HostInfo',
            fields=[
                ('IP', models.GenericIPAddressField(db_index=True, primary_key=True, serialize=False)),
                ('hostname', models.CharField(max_length=32)),
                ('type', models.SmallIntegerField(choices=[(0, '\u7269\u7406\u5bbf\u4e3b\u673a'), (1, 'kvm\u865a\u62df\u673a'), (2, 'docker\u865a\u62df\u673a'), (3, 'pc\u673a')], default=1, verbose_name='\u4e3b\u673a\u7c7b\u578b')),
                ('mem', models.CharField(max_length=16, verbose_name='\u603b\u5185\u5b58G')),
                ('disk', models.CharField(max_length=64, verbose_name='\u78c1\u76d8\u60c5\u51b5')),
                ('remarks', models.TextField(verbose_name='\u8bf4\u660e')),
                ('create_time', models.DateTimeField(verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('destory_tiime', models.DateTimeField(null=True, verbose_name='\u9500\u6bc1\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u4e3b\u673a\u4fe1\u606f',
                'verbose_name_plural': '\u4e3b\u673a\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tomcat_name', models.CharField(max_length=16, verbose_name='tomcat\u540d\u79f0')),
                ('service_name', models.CharField(max_length=16, verbose_name='\u9879\u76ee\u540d\u79f0')),
            ],
            options={
                'verbose_name': '\u9879\u76ee\u670d\u52a1',
                'verbose_name_plural': '\u9879\u76ee\u670d\u52a1',
            },
        ),
        migrations.AddField(
            model_name='hostinfo',
            name='labels',
            field=models.ManyToManyField(to='hostinfo.Services'),
        ),
    ]
