# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-28 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostinfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostinfo',
            name='own_to',
            field=models.GenericIPAddressField(default=None, null=True),
        ),
    ]
